<?php

namespace App\Services\Translation;

use App\Models\SystemTranslation;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;

class TranslationManagementService
{
    public function __construct(
        protected TranslationCacheService $translationCache
    ) {
    }

    /**
     * Build locale-matrix list payload for admin translation management.
     *
     * @param array<string, mixed> $filters
     *
     * @return array{
     *     items: Collection<int, array<string, mixed>>,
     *     meta: array<string, mixed>
     * }
     */
    public function listForApi(array $filters = []): array
    {
        $perPage = $this->normalizePerPage($filters['per_page'] ?? 10);
        $search = trim((string) ($filters['search'] ?? ''));
        $locale = trim((string) ($filters['locale'] ?? ''));
        $group = trim((string) ($filters['group'] ?? ''));
        $source = trim((string) ($filters['source'] ?? ''));
        $translatedOnly = filter_var($filters['translated_only'] ?? false, FILTER_VALIDATE_BOOLEAN);
        $autogeneratedOnly = filter_var($filters['autogenerated_only'] ?? false, FILTER_VALIDATE_BOOLEAN);
        $active = $filters['active'] ?? null;

        $query = SystemTranslation::query()
            ->select([
                DB::raw('MIN(id) as id'),
                'group',
                'key',
                'source',
                DB::raw('MAX(updated_at) as updated_at'),
                DB::raw('MAX(CASE WHEN is_auto_generated = 1 THEN 1 ELSE 0 END) as is_auto_generated'),
                DB::raw('MIN(CASE WHEN is_active = 1 THEN 1 ELSE 0 END) as is_active'),
                DB::raw('MIN(CASE WHEN is_translated = 1 THEN 1 ELSE 0 END) as is_translated'),
            ])
            ->groupBy('group', 'key', 'source')
            ->when($group !== '', fn ($builder) => $builder->where('group', $group))
            ->when($source !== '', fn ($builder) => $builder->where('source', $source))
            ->when($locale !== '', fn ($builder) => $builder->where('locale', $locale))
            ->when($translatedOnly, fn ($builder) => $builder->where('is_translated', true))
            ->when($autogeneratedOnly, fn ($builder) => $builder->where('is_auto_generated', true))
            ->when($active !== null && $active !== '', fn ($builder) => $builder->where('is_active', filter_var($active, FILTER_VALIDATE_BOOLEAN)))
            ->when($search !== '', function ($builder) use ($search): void {
                $builder->where(function ($nested) use ($search): void {
                    $nested->where('group', 'like', "%{$search}%")
                        ->orWhere('key', 'like', "%{$search}%")
                        ->orWhere('value', 'like', "%{$search}%");
                });
            })
            ->orderBy('group')
            ->orderBy('key');

        $paginator = $query->paginate($perPage);
        $rows = collect($paginator->items());
        $pairs = $rows->map(fn ($row) => [
            'group' => $row->group,
            'key' => $row->key,
            'source' => $row->source,
        ])->values();

        $localesByPair = $this->loadLocalesForPairs($pairs);

        $items = $rows->map(function ($row) use ($localesByPair) {
            $index = $row->group . '::' . $row->key . '::' . $row->source;
            return [
                'id' => (int) $row->id,
                'group' => $row->group,
                'key' => $row->key,
                'source' => $row->source,
                'is_translated' => (bool) $row->is_translated,
                'is_auto_generated' => (bool) $row->is_auto_generated,
                'is_active' => (bool) $row->is_active,
                'updated_at' => $row->updated_at,
                'locales' => $localesByPair[$index] ?? [],
            ];
        })->values();

        return [
            'items' => $items,
            'meta' => [
                'current_page' => $paginator->currentPage(),
                'last_page' => $paginator->lastPage(),
                'per_page' => $paginator->perPage(),
                'total' => $paginator->total(),
                'groups' => SystemTranslation::query()
                    ->select('group')
                    ->distinct()
                    ->orderBy('group')
                    ->pluck('group')
                    ->values()
                    ->all(),
                'sources' => SystemTranslation::query()
                    ->select('source')
                    ->distinct()
                    ->orderBy('source')
                    ->pluck('source')
                    ->values()
                    ->all(),
                'locales' => SystemTranslation::query()
                    ->select('locale')
                    ->distinct()
                    ->orderBy('locale')
                    ->pluck('locale')
                    ->values()
                    ->all(),
            ],
        ];
    }

    /**
     * Create new translation matrix rows.
     *
     * @param array<string, mixed> $payload
     */
    public function create(array $payload): void
    {
        $group = $payload['group'];
        $key = $payload['key'];
        $source = $payload['source'] ?? 'database';
        $isActive = (bool) ($payload['is_active'] ?? true);
        $isAutoGenerated = (bool) ($payload['is_auto_generated'] ?? false);
        $description = $payload['description'] ?? null;
        $values = $payload['values'] ?? [];

        DB::transaction(function () use ($group, $key, $source, $isActive, $isAutoGenerated, $description, $values): void {
            foreach ($values as $locale => $value) {
                if (!is_string($locale) || trim($locale) === '' || $value === null || trim((string) $value) === '') {
                    continue;
                }

                SystemTranslation::query()->updateOrCreate(
                    [
                        'locale' => $locale,
                        'group' => $group,
                        'key' => $key,
                    ],
                    [
                        'value' => trim((string) $value),
                        'source' => $source,
                        'description' => $description,
                        'is_active' => $isActive,
                        'is_auto_generated' => $isAutoGenerated,
                        'is_translated' => !$isAutoGenerated,
                        'is_frontend' => true,
                        'is_backend' => true,
                        'updated_by' => auth()->id(),
                        'created_by' => auth()->id(),
                    ]
                );
            }
        });

        $this->invalidateTranslationCaches($group, $key, array_keys($values));
    }

    /**
     * Update existing translation matrix rows.
     *
     * @param array<string, mixed> $payload
     */
    public function updateById(int $translationId, array $payload): void
    {
        $seed = SystemTranslation::query()->findOrFail($translationId);

        $source = $payload['source'] ?? $seed->source;
        $description = $payload['description'] ?? $seed->description;
        $isActive = (bool) ($payload['is_active'] ?? $seed->is_active);
        $isAutoGenerated = (bool) ($payload['is_auto_generated'] ?? $seed->is_auto_generated);
        $values = $payload['values'] ?? [];

        DB::transaction(function () use ($seed, $source, $description, $isActive, $isAutoGenerated, $values): void {
            foreach ($values as $locale => $value) {
                if (!is_string($locale) || trim($locale) === '') {
                    continue;
                }

                $rowPayload = [
                    'source' => $source,
                    'description' => $description,
                    'is_active' => $isActive,
                    'is_auto_generated' => $isAutoGenerated,
                    'is_translated' => $value !== null && trim((string) $value) !== '',
                    'is_frontend' => true,
                    'is_backend' => true,
                    'updated_by' => auth()->id(),
                ];

                if ($value !== null && trim((string) $value) !== '') {
                    $rowPayload['value'] = trim((string) $value);
                    $rowPayload['created_by'] = auth()->id();

                    SystemTranslation::query()->updateOrCreate(
                        [
                            'locale' => $locale,
                            'group' => $seed->group,
                            'key' => $seed->key,
                        ],
                        $rowPayload,
                    );
                }
            }
        });

        $this->invalidateTranslationCaches($seed->group, $seed->key, array_keys($values));
    }

    /**
     * Delete full translation matrix by seed row id.
     */
    public function deleteById(int $translationId): void
    {
        $seed = SystemTranslation::query()->findOrFail($translationId);

        $locales = SystemTranslation::query()
            ->where('group', $seed->group)
            ->where('key', $seed->key)
            ->pluck('locale')
            ->unique()
            ->values()
            ->all();

        SystemTranslation::query()
            ->where('group', $seed->group)
            ->where('key', $seed->key)
            ->where('source', $seed->source)
            ->delete();

        $this->invalidateTranslationCaches($seed->group, $seed->key, $locales);
    }

    /**
     * @param Collection<int, array{group:string,key:string,source:string}> $pairs
     * @return array<string, array<string, array<string, mixed>>>
     */
    protected function loadLocalesForPairs(Collection $pairs): array
    {
        $localesByPair = [];

        if ($pairs->isEmpty()) {
            return $localesByPair;
        }

        $translations = SystemTranslation::query()
            ->where(function ($builder) use ($pairs): void {
                foreach ($pairs as $pair) {
                    $builder->orWhere(function ($nested) use ($pair): void {
                        $nested->where('group', $pair['group'])
                            ->where('key', $pair['key'])
                            ->where('source', $pair['source']);
                    });
                }
            })
            ->orderBy('locale')
            ->get([
                'id',
                'locale',
                'group',
                'key',
                'source',
                'value',
                'is_translated',
                'is_auto_generated',
                'is_active',
                'updated_at',
                'description',
            ]);

        foreach ($translations as $translation) {
            $index = $translation->group . '::' . $translation->key . '::' . $translation->source;
            $localesByPair[$index] ??= [];
            $localesByPair[$index][$translation->locale] = [
                'id' => $translation->id,
                'locale' => $translation->locale,
                'value' => $translation->value,
                'is_translated' => (bool) $translation->is_translated,
                'is_auto_generated' => (bool) $translation->is_auto_generated,
                'is_active' => (bool) $translation->is_active,
                'description' => $translation->description,
                'updated_at' => optional($translation->updated_at)?->toISOString(),
            ];
        }

        return $localesByPair;
    }

    /**
     * Invalidate all cache entries that can contain updated translation rows.
     *
     * @param array<int, mixed> $candidateLocales
     */
    protected function invalidateTranslationCaches(string $group, string $key, array $candidateLocales = []): void
    {
        $persistedLocales = SystemTranslation::query()
            ->where('group', $group)
            ->where('key', $key)
            ->pluck('locale')
            ->unique()
            ->values()
            ->all();

        $locales = array_values(array_unique(array_merge($persistedLocales, $candidateLocales)));

        foreach ($locales as $locale) {
            $this->translationCache->forget((string) $locale, $group, $key);
            $this->translationCache->forgetPreload((string) $locale, $group);
            $this->translationCache->forgetPreload((string) $locale);
        }
    }

    protected function normalizePerPage(mixed $value): int
    {
        return min(max((int) $value, 5), 100);
    }
}

