<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Dynamic runtime translation entity.
 *
 * WHY:
 * Stores database-driven translations used for:
 * - RBAC labels
 * - settings labels
 * - dashboard widgets
 * - notifications
 * - runtime/business localization
 *
 * IMPORTANT:
 * Static UI translations should still remain
 * inside Laravel/Vue lang files.
 */
class SystemTranslation extends Model
{
    /**
     * Mass assignable attributes.
     */
    protected $fillable = [
        'locale',
        'group',
        'key',
        'value',

        'source',
        'description',

        'is_frontend',
        'is_backend',

        'is_system',
        'is_active',

        'is_auto_generated',
        'is_translated',

        'created_by',
        'updated_by',
    ];

    /**
     * Attribute casting.
     */
    protected $casts = [
        'is_frontend' => 'boolean',
        'is_backend' => 'boolean',

        'is_system' => 'boolean',
        'is_active' => 'boolean',

        'is_auto_generated' => 'boolean',
        'is_translated' => 'boolean',
    ];

    /*
    |--------------------------------------------------------------------------
    | Relationships
    |--------------------------------------------------------------------------
    */

    /**
     * User who created translation.
     */
    public function creator(): BelongsTo
    {
        return $this->belongsTo(
            User::class,
            'created_by'
        );
    }

    /**
     * User who updated translation.
     */
    public function updater(): BelongsTo
    {
        return $this->belongsTo(
            User::class,
            'updated_by'
        );
    }

    /*
    |--------------------------------------------------------------------------
    | Scopes
    |--------------------------------------------------------------------------
    */

    /**
     * Active translations only.
     */
    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }

    /**
     * Frontend translations only.
     */
    public function scopeFrontend($query)
    {
        return $query->where('is_frontend', true);
    }

    /**
     * Backend translations only.
     */
    public function scopeBackend($query)
    {
        return $query->where('is_backend', true);
    }

    /**
     * Missing/non-translated entries.
     */
    public function scopeMissing($query)
    {
        return $query->where('is_translated', false);
    }

    /**
     * Auto-generated translations.
     */
    public function scopeAutoGenerated($query)
    {
        return $query->where('is_auto_generated', true);
    }
}
