<template>
  <section class="translations-page">
    <header class="translations-page__header c-card">
      <div>
        <h2 class="translations-page__title">{{ t('common.translationsPage.title') }}</h2>
        <p class="translations-page__subtitle">{{ t('common.translationsPage.subtitle') }}</p>
      </div>
      <div class="translations-page__header-actions">
        <span class="translations-page__stat">{{ t('common.labels.total') }}: {{ meta.total }}</span>
        <button type="button" class="translations-page__create-btn" @click="openCreateModal">{{ t('common.translationsPage.createTranslation') }}</button>
      </div>
    </header>

    <TranslationsFilters
      :search="query.search"
      :locale="query.locale"
      :group="query.group"
      :source="query.source"
      :translated-only="query.translatedOnly"
      :autogenerated-only="query.autogeneratedOnly"
      :active="query.active"
      :locales="meta.locales"
      :groups="meta.groups"
      :sources="meta.sources"
      @update:search="onSearchChange"
      @update:locale="onLocaleChange"
      @update:group="onGroupChange"
      @update:source="onSourceChange"
      @update:translated-only="onTranslatedOnlyChange"
      @update:autogenerated-only="onAutogeneratedOnlyChange"
      @update:active="onActiveChange"
    />

    <section class="c-card translations-page__table-wrap">
      <div v-if="isLoading" class="translations-page__state"><BaseLoader :label="t('common.translationsPage.loadingTranslations')" /></div>

      <BaseErrorState v-else-if="errorMessage" :title="t('common.translationsPage.failedLoadTranslations')" :description="errorMessage">
        <button type="button" class="translations-page__retry" @click="loadTranslations">{{ t('common.actions.retry') }}</button>
      </BaseErrorState>

      <template v-else>
        <BaseTable :columns="tableColumns" :rows="rows" row-key="id">
          <template #empty>
            <BaseEmptyState :title="t('common.translationsPage.noTranslationsFound')" :description="t('common.translationsPage.noTranslationsHint')" />
          </template>

          <template #cell:key="{ row }">
            <div class="translations-main-cell">
              <div class="translations-main-cell__key">{{ row.key }}</div>
              <div class="translations-main-cell__meta">{{ row.group }} · {{ row.source }}</div>
            </div>
          </template>

          <template #cell:state="{ row }">
            <div class="state-badges">
              <span class="state-badge" :class="row.is_translated ? 'is-ok' : 'is-warn'">{{ row.is_translated ? t('common.translationsPage.translated') : t('common.translationsPage.untranslated') }}</span>
              <span v-if="row.is_auto_generated" class="state-badge is-auto">{{ t('common.translationsPage.autoGenerated') }}</span>
              <span class="state-badge" :class="row.is_active ? 'is-active' : 'is-inactive'">{{ row.is_active ? t('common.labels.active') : t('common.labels.inactive') }}</span>
            </div>
          </template>

          <template v-for="localeCode in enabledLocaleCodes" :key="`locale-cell-${localeCode}`" #[`cell:locale_${localeCode}`]="{ row }">
            <div class="locale-preview" :class="{ 'is-missing': !row.locales?.[localeCode]?.value }">
              {{ row.locales?.[localeCode]?.value || t('common.translationsPage.missing') }}
            </div>
          </template>

          <template #cell:updated_at="{ row }">
            {{ formatDate(row.updated_at) }}
          </template>

          <template #cell:actions="{ row }">
            <TranslationsRowActions @action="(action) => handleRowAction(action, row as TranslationRow)" />
          </template>
        </BaseTable>

        <footer class="translations-page__footer">
          <UsersPagination
            :current-page="meta.current_page"
            :total-pages="meta.last_page"
            :per-page="query.perPage"
            :total-items="meta.total"
            :range-start="visibleRange.start"
            :range-end="visibleRange.end"
            @change="onPageChange"
            @update:per-page="onPerPageChange"
          />
        </footer>
      </template>
    </section>
  </section>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { useI18n } from 'vue-i18n';

import TranslationsFilters from '../components/TranslationsFilters.vue';
import TranslationsRowActions from '../components/TranslationsRowActions.vue';
import TranslationUpsertModal from '../components/TranslationUpsertModal.vue';
import { translationsService } from '../services/translations.service';
import type { TranslationRow, TranslationsMeta, TranslationsQuery } from '../types/translations.types';
import BaseEmptyState from '../../../shared/components/ui/BaseEmptyState.vue';
import BaseErrorState from '../../../shared/components/ui/BaseErrorState.vue';
import BaseLoader from '../../../shared/components/ui/BaseLoader.vue';
import BaseTable, { type BaseTableColumn } from '../../../shared/components/ui/BaseTable.vue';
import UsersPagination from '../../users/components/UsersPagination.vue';
import { useConfirm } from '../../../shared/confirm';
import { getEnabledLocales } from '../../../shared/i18n';
import { useModal } from '../../../shared/modal';
import { useToast } from '../../../shared/toast';

const { t, locale } = useI18n({ useScope: 'global' });
const modal = useModal();
const confirm = useConfirm();
const toast = useToast();
const isLoading = ref(true);
const errorMessage = ref('');
const rows = ref<TranslationRow[]>([]);
const enabledLocaleCodes = getEnabledLocales().map((item) => item.code);
const query = ref<TranslationsQuery>({
  search: '',
  locale: 'all',
  group: 'all',
  source: 'all',
  translatedOnly: false,
  autogeneratedOnly: false,
  active: 'all',
  page: 1,
  perPage: 10,
});

const meta = ref<TranslationsMeta>({
  current_page: 1,
  last_page: 1,
  per_page: 10,
  total: 0,
  groups: [],
  sources: [],
  locales: enabledLocaleCodes,
});

let searchDebounce: ReturnType<typeof setTimeout> | undefined;

const tableColumns = computed<BaseTableColumn[]>(() => [
  { key: 'key', label: t('common.translationsPage.keyColumn') },
  ...enabledLocaleCodes.map((localeCode) => ({ key: `locale_${localeCode}`, label: localeCode.toUpperCase() })),
  { key: 'state', label: t('common.translationsPage.stateColumn'), width: '220px' },
  { key: 'updated_at', label: t('common.translationsPage.updatedAt'), width: '120px' },
  { key: 'actions', label: t('common.actions.actions'), width: '100px', align: 'right' },
]);

const visibleRange = computed(() => {
  if (meta.value.total === 0) return { start: 0, end: 0 };
  const start = (meta.value.current_page - 1) * query.value.perPage + 1;
  const end = Math.min(meta.value.current_page * query.value.perPage, meta.value.total);
  return { start, end };
});

const formatDate = (value: string | null): string => {
  if (!value) return '-';
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) return '-';
  return new Intl.DateTimeFormat(locale.value, { month: 'short', day: '2-digit', year: 'numeric' }).format(parsed);
};

const toParams = () => ({
  search: query.value.search || undefined,
  locale: query.value.locale !== 'all' ? query.value.locale : undefined,
  group: query.value.group !== 'all' ? query.value.group : undefined,
  source: query.value.source !== 'all' ? query.value.source : undefined,
  translated_only: query.value.translatedOnly || undefined,
  autogenerated_only: query.value.autogeneratedOnly || undefined,
  active: query.value.active !== 'all' ? String(query.value.active === 'active') : undefined,
  page: query.value.page,
  per_page: query.value.perPage,
});

const loadTranslations = async (): Promise<void> => {
  try {
    isLoading.value = true;
    errorMessage.value = '';

    const result = await translationsService.fetchTranslations(toParams());
    rows.value = result.items;
    meta.value = result.meta;
  } catch (error) {
    errorMessage.value = (error as { message?: string })?.message ?? 'Unable to fetch translations.';
  } finally {
    isLoading.value = false;
  }
};

const openCreateModal = (): void => {
  modal.open({
    component: TranslationUpsertModal,
    title: t('common.translationsPage.createTitle'),
    subtitle: t('common.translationsPage.createSubtitle'),
    size: 'xl',
    props: {
      mode: 'create',
      locales: meta.value.locales.length > 0 ? meta.value.locales : enabledLocaleCodes,
      onSaved: () => void loadTranslations(),
    },
  });
};

const openEditModal = (row: TranslationRow): void => {
  modal.open({
    component: TranslationUpsertModal,
    title: t('common.translationsPage.editTitle'),
    subtitle: `${row.group}.${row.key}`,
    size: 'xl',
    props: {
      mode: 'edit',
      row,
      locales: meta.value.locales.length > 0 ? meta.value.locales : enabledLocaleCodes,
      onSaved: () => void loadTranslations(),
    },
  });
};

const handleRowAction = async (action: 'edit' | 'delete', row: TranslationRow): Promise<void> => {
  if (action === 'edit') {
    openEditModal(row);
    return;
  }

  const accepted = await confirm.open({
    title: t('common.translationsPage.deleteTitle'),
    message: t('common.translationsPage.deleteMessage', { key: `${row.group}.${row.key}` }),
    variant: 'danger',
    confirmLabel: t('common.actions.delete'),
    cancelLabel: t('common.actions.cancel'),
    destructive: true,
  });

  if (!accepted) return;

  try {
    await translationsService.deleteTranslation(row.id);
    toast.success({ title: t('common.translationsPage.deleted'), message: t('common.translationsPage.deletedHint') });
    await loadTranslations();
  } catch {
    toast.error({ title: t('common.translationsPage.deleteFailed'), message: t('common.translationsPage.deleteFailedHint') });
  }
};

const onSearchChange = (value: string): void => {
  if (searchDebounce) clearTimeout(searchDebounce);
  searchDebounce = setTimeout(() => {
    query.value.search = value;
    query.value.page = 1;
    void loadTranslations();
  }, 250);
};

const onLocaleChange = (value: string): void => { query.value.locale = value; query.value.page = 1; void loadTranslations(); };
const onGroupChange = (value: string): void => { query.value.group = value; query.value.page = 1; void loadTranslations(); };
const onSourceChange = (value: string): void => { query.value.source = value; query.value.page = 1; void loadTranslations(); };
const onTranslatedOnlyChange = (value: boolean): void => { query.value.translatedOnly = value; query.value.page = 1; void loadTranslations(); };
const onAutogeneratedOnlyChange = (value: boolean): void => { query.value.autogeneratedOnly = value; query.value.page = 1; void loadTranslations(); };
const onActiveChange = (value: 'all' | 'active' | 'inactive'): void => { query.value.active = value; query.value.page = 1; void loadTranslations(); };
const onPageChange = (page: number): void => { query.value.page = page; void loadTranslations(); };
const onPerPageChange = (size: number): void => { query.value.perPage = size; query.value.page = 1; void loadTranslations(); };

onMounted(() => {
  void loadTranslations();
});
</script>

<style scoped>
.translations-page{display:grid;gap:12px}
.translations-page__header{margin-top:0;display:flex;align-items:flex-start;justify-content:space-between;gap:10px}
.translations-page__title{margin:0;font-size:18px;color:#f8fafc}
.translations-page__subtitle{margin:6px 0 0;color:#94a3b8;font-size:13px}
.translations-page__header-actions{display:flex;align-items:center;gap:8px}
.translations-page__stat{border-radius:999px;border:1px solid rgba(71,85,105,.6);padding:4px 9px;font-size:11px;color:#cbd5e1}
.translations-page__create-btn{height:32px;border-radius:8px;border:1px solid rgba(16,185,129,.55);background:rgba(16,185,129,.2);color:#6ee7b7;padding:0 11px;font-size:12px;font-weight:600}
.translations-page__table-wrap{margin-top:0;display:grid;gap:10px}
.translations-page__state{padding:14px 0}
.translations-page__retry{height:32px;border-radius:8px;border:1px solid rgba(71,85,105,.55);background:rgba(15,23,42,.7);color:#e2e8f0;padding:0 11px}
.translations-main-cell{min-width:220px}
.translations-main-cell__key{color:#f8fafc;font-weight:600}
.translations-main-cell__meta{color:#94a3b8;font-size:11px}
.locale-preview{font-size:12px;color:#dbeafe;max-width:260px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.locale-preview.is-missing{color:#fcd34d;font-style:italic}
.state-badges{display:flex;gap:6px;flex-wrap:wrap}
.state-badge{font-size:10px;border-radius:999px;padding:2px 8px;border:1px solid rgba(71,85,105,.45);color:#94a3b8;background:rgba(15,23,42,.45)}
.state-badge.is-ok{border-color:rgba(34,197,94,.55);color:#bbf7d0;background:rgba(22,163,74,.16)}
.state-badge.is-warn{border-color:rgba(245,158,11,.55);color:#fcd34d;background:rgba(180,83,9,.16)}
.state-badge.is-auto{border-color:rgba(59,130,246,.55);color:#bfdbfe;background:rgba(59,130,246,.16)}
.state-badge.is-active{border-color:rgba(16,185,129,.55);color:#6ee7b7;background:rgba(16,185,129,.16)}
.state-badge.is-inactive{border-color:rgba(148,163,184,.55);color:#cbd5e1;background:rgba(51,65,85,.4)}
.translations-page__footer{display:flex;justify-content:flex-end}
@media (max-width:760px){.translations-page__header{flex-direction:column}.translations-page__footer{justify-content:flex-start}}
</style>
