<template>
  <section class="translations-filters c-card">
    <div class="translations-filters__search">
      <label class="translations-filters__label">{{ t('common.labels.search') }}</label>
      <input :value="search" class="translations-filters__input" :placeholder="t('common.translationsPage.searchPlaceholder')" @input="emit('update:search', ($event.target as HTMLInputElement).value)" />
    </div>

    <div class="translations-filters__group">
      <label class="translations-filters__label">{{ t('common.translationsPage.locale') }}</label>
      <BaseDropdown>
        <template #trigger="{ isOpen }"><button type="button" class="translations-filters__trigger">{{ localeLabel }} <span>{{ isOpen ? '^' : 'v' }}</span></button></template>
        <template #default="{ close }">
          <button v-for="option in localeOptions" :key="option.value" type="button" class="translations-filters__option" :class="{ 'is-active': option.value === locale }" @click="selectLocale(option.value, close)">{{ option.label }}</button>
        </template>
      </BaseDropdown>
    </div>

    <div class="translations-filters__group">
      <label class="translations-filters__label">{{ t('common.translationsPage.group') }}</label>
      <BaseDropdown>
        <template #trigger="{ isOpen }"><button type="button" class="translations-filters__trigger">{{ groupLabel }} <span>{{ isOpen ? '^' : 'v' }}</span></button></template>
        <template #default="{ close }">
          <button v-for="option in groupOptions" :key="option.value" type="button" class="translations-filters__option" :class="{ 'is-active': option.value === group }" @click="selectGroup(option.value, close)">{{ option.label }}</button>
        </template>
      </BaseDropdown>
    </div>

    <div class="translations-filters__group">
      <label class="translations-filters__label">{{ t('common.translationsPage.source') }}</label>
      <BaseDropdown>
        <template #trigger="{ isOpen }"><button type="button" class="translations-filters__trigger">{{ sourceLabel }} <span>{{ isOpen ? '^' : 'v' }}</span></button></template>
        <template #default="{ close }">
          <button v-for="option in sourceOptions" :key="option.value" type="button" class="translations-filters__option" :class="{ 'is-active': option.value === source }" @click="selectSource(option.value, close)">{{ option.label }}</button>
        </template>
      </BaseDropdown>
    </div>

    <div class="translations-filters__flags">
      <label class="translations-flag">
        <input type="checkbox" :checked="translatedOnly" @change="emit('update:translatedOnly', ($event.target as HTMLInputElement).checked)" />
        <span>{{ t('common.translationsPage.translatedOnly') }}</span>
      </label>
      <label class="translations-flag">
        <input type="checkbox" :checked="autogeneratedOnly" @change="emit('update:autogeneratedOnly', ($event.target as HTMLInputElement).checked)" />
        <span>{{ t('common.translationsPage.autogeneratedOnly') }}</span>
      </label>
    </div>

    <div class="translations-filters__group">
      <label class="translations-filters__label">{{ t('common.labels.status') }}</label>
      <BaseDropdown>
        <template #trigger="{ isOpen }"><button type="button" class="translations-filters__trigger">{{ activeLabel }} <span>{{ isOpen ? '^' : 'v' }}</span></button></template>
        <template #default="{ close }">
          <button v-for="option in activeOptions" :key="option.value" type="button" class="translations-filters__option" :class="{ 'is-active': option.value === active }" @click="selectActive(option.value, close)">{{ option.label }}</button>
        </template>
      </BaseDropdown>
    </div>
  </section>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';
import BaseDropdown from '../../../shared/components/ui/BaseDropdown.vue';

const props = defineProps<{
  search: string;
  locale: string;
  group: string;
  source: string;
  translatedOnly: boolean;
  autogeneratedOnly: boolean;
  active: 'all' | 'active' | 'inactive';
  locales: string[];
  groups: string[];
  sources: string[];
}>();

const emit = defineEmits<{
  'update:search': [value: string];
  'update:locale': [value: string];
  'update:group': [value: string];
  'update:source': [value: string];
  'update:translatedOnly': [value: boolean];
  'update:autogeneratedOnly': [value: boolean];
  'update:active': [value: 'all' | 'active' | 'inactive'];
}>();

const { t } = useI18n({ useScope: 'global' });

const localeOptions = computed(() => [{ value: 'all', label: t('common.translationsPage.allLocales') }, ...props.locales.map((l) => ({ value: l, label: l.toUpperCase() }))]);
const groupOptions = computed(() => [{ value: 'all', label: t('common.translationsPage.allGroups') }, ...props.groups.map((g) => ({ value: g, label: g }))]);
const sourceOptions = computed(() => [{ value: 'all', label: t('common.translationsPage.allSources') }, ...props.sources.map((s) => ({ value: s, label: s }))]);

const localeLabel = computed(() => localeOptions.value.find((opt) => opt.value === props.locale)?.label ?? t('common.translationsPage.allLocales'));
const groupLabel = computed(() => groupOptions.value.find((opt) => opt.value === props.group)?.label ?? t('common.translationsPage.allGroups'));
const sourceLabel = computed(() => sourceOptions.value.find((opt) => opt.value === props.source)?.label ?? t('common.translationsPage.allSources'));
const activeOptions = computed(() => [
  { value: 'all', label: t('common.labels.allStatuses') },
  { value: 'active', label: t('common.labels.active') },
  { value: 'inactive', label: t('common.labels.inactive') },
]);
const activeLabel = computed(() => activeOptions.value.find((opt) => opt.value === props.active)?.label ?? t('common.labels.allStatuses'));

const selectLocale = (value: string, close: () => void): void => { emit('update:locale', value); close(); };
const selectGroup = (value: string, close: () => void): void => { emit('update:group', value); close(); };
const selectSource = (value: string, close: () => void): void => { emit('update:source', value); close(); };
const selectActive = (value: 'all' | 'active' | 'inactive', close: () => void): void => { emit('update:active', value); close(); };
</script>

<style scoped>
.translations-filters{margin-top:0;display:grid;grid-template-columns:minmax(220px,1fr) repeat(4,minmax(140px,180px));gap:10px;align-items:end}
.translations-filters__label{display:block;margin-bottom:5px;font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:#94a3b8;font-weight:700}
.translations-filters__input{width: calc(100% - 20px);height:36px;border-radius:9px;border:1px solid rgba(71,85,105,.6);background:rgba(15,23,42,.7);color:#e2e8f0;padding:0 10px;font-size:13px}
.translations-filters__trigger{width:100%;height:36px;border-radius:8px;border:1px solid rgba(71,85,105,.6);background:rgba(15,23,42,.7);color:#e2e8f0;padding:0 10px;font-size:12px;display:inline-flex;justify-content:space-between;align-items:center}
.translations-filters__option{width:100%;text-align:left;border:0;background:transparent;color:#e2e8f0;border-radius:7px;padding:8px 10px;font-size:12px}
.translations-filters__option:hover{background:rgba(51,65,85,.75)}
.translations-filters__option.is-active{background:rgba(51,65,85,.95);font-weight:700}
.translations-filters__flags{display:flex;align-items:center;gap:12px;flex-wrap:wrap}
.translations-flag{display:inline-flex;align-items:center;gap:6px;color:#cbd5e1;font-size:12px}
@media (max-width:1080px){.translations-filters{grid-template-columns:1fr}}
</style>
