<template>
  <BaseForm :model="form.model" @submit="handleSubmit">
    <BaseFormSection :title="mode === 'create' ? t('common.translationsPage.createTitle') : t('common.translationsPage.editTitle')" layout="grid">
      <BaseFormField :label="t('common.translationsPage.group')" :required="true" :error="form.getFieldError('group')">
        <input :disabled="mode === 'edit'" :value="String(form.model.group)" @input="form.setField('group', ($event.target as HTMLInputElement).value)" />
      </BaseFormField>
      <BaseFormField :label="t('common.translationsPage.key')" :required="true" :error="form.getFieldError('key')">
        <input :disabled="mode === 'edit'" :value="String(form.model.key)" @input="form.setField('key', ($event.target as HTMLInputElement).value)" />
      </BaseFormField>
      <BaseFormField :label="t('common.translationsPage.source')">
        <input :value="String(form.model.source)" @input="form.setField('source', ($event.target as HTMLInputElement).value)" />
      </BaseFormField>
      <BaseFormField :label="t('common.translationsPage.description')">
        <input :value="String(form.model.description ?? '')" @input="form.setField('description', ($event.target as HTMLInputElement).value)" />
      </BaseFormField>
      <BaseFormField :label="t('common.translationsPage.active')">
        <label class="toggle"><input type="checkbox" :checked="Boolean(form.model.is_active)" @change="form.setField('is_active', ($event.target as HTMLInputElement).checked)" /><span>{{ t('common.translationsPage.active') }}</span></label>
      </BaseFormField>
      <BaseFormField :label="t('common.translationsPage.autoGenerated')">
        <label class="toggle"><input type="checkbox" :checked="Boolean(form.model.is_auto_generated)" @change="form.setField('is_auto_generated', ($event.target as HTMLInputElement).checked)" /><span>{{ t('common.translationsPage.autoGenerated') }}</span></label>
      </BaseFormField>
    </BaseFormSection>

    <BaseFormSection :title="t('common.translationsPage.localeValues')" :description="t('common.translationsPage.localeValuesHint')">
      <div class="locale-grid">
        <div v-for="locale in locales" :key="locale" class="locale-cell" :class="{ 'is-missing': !values[locale] }">
          <label>{{ locale.toUpperCase() }}</label>
          <textarea rows="3" :value="values[locale]" @input="setLocaleValue(locale, ($event.target as HTMLTextAreaElement).value)" />
        </div>
      </div>
    </BaseFormSection>

    <BaseFormActions :loading="asyncForm.isSubmitting.value" :submit-disabled="!form.isDirty.value" @cancel="props.closeModal?.()" />
  </BaseForm>
</template>

<script setup lang="ts">
import { reactive } from 'vue';
import { useI18n } from 'vue-i18n';

import type { FormSubmitContext } from '../../../shared/forms';
import { BaseForm, BaseFormActions, BaseFormField, BaseFormSection, useAsyncForm, useForm } from '../../../shared/forms';
import { isNormalizedApiError } from '../../../services/api/interceptors';
import { useToast } from '../../../shared/toast';
import { translationsService } from '../services/translations.service';
import type { TranslationRow } from '../types/translations.types';

const props = defineProps<{
  mode: 'create' | 'edit';
  locales: string[];
  row?: TranslationRow;
  closeModal?: () => void;
  onSaved?: () => void;
}>();

const { t } = useI18n({ useScope: 'global' });
const toast = useToast();
const asyncForm = useAsyncForm();

const form = useForm({
  group: props.row?.group ?? '',
  key: props.row?.key ?? '',
  source: props.row?.source ?? 'database',
  description: props.row?.locales?.[props.locales[0] ?? '']?.description ?? '',
  is_active: props.row?.is_active ?? true,
  is_auto_generated: props.row?.is_auto_generated ?? false,
});

const values = reactive<Record<string, string>>(
  Object.fromEntries(props.locales.map((locale) => [locale, props.row?.locales?.[locale]?.value ?? ''])),
);

const setLocaleValue = (locale: string, value: string): void => {
  values[locale] = value;
  form.setField('source', String(form.model.source));
};

const handleSubmit = async ({ model }: FormSubmitContext<Record<string, unknown>>): Promise<void> => {
  form.clearErrors();

  const payload = {
    group: String(model.group ?? '').trim(),
    key: String(model.key ?? '').trim(),
    source: String(model.source ?? 'database').trim() || 'database',
    description: String(model.description ?? '').trim() || null,
    is_active: Boolean(model.is_active),
    is_auto_generated: Boolean(model.is_auto_generated),
    values: Object.fromEntries(props.locales.map((locale) => [locale, values[locale] ?? ''])),
  };

  const result = await asyncForm.submit(async () => {
    if (props.mode === 'create') {
      await translationsService.createTranslation(payload);
    } else if (props.row) {
      await translationsService.updateTranslation(props.row.id, {
        source: payload.source,
        description: payload.description,
        is_active: payload.is_active,
        is_auto_generated: payload.is_auto_generated,
        values: payload.values,
      });
    }

    return true;
  });

  if (!result) {
    const error = asyncForm.lastError.value;
    if (isNormalizedApiError(error) && error.code === 'validation' && error.errors) {
      form.setErrors(error.errors);
    }
    toast.error({ title: t('common.translationsPage.saveFailed'), message: t('common.translationsPage.saveFailedHint') });
    return;
  }

  toast.success({ title: t('common.translationsPage.saved'), message: t('common.translationsPage.savedHint') });
  props.onSaved?.();
  props.closeModal?.();
};
</script>

<style scoped>
.toggle{display:inline-flex;align-items:center;gap:8px;color:#cbd5e1}
.locale-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}
.locale-cell{display:grid;gap:6px;padding:8px;border-radius:10px;border:1px solid rgba(71,85,105,.55);background:rgba(15,23,42,.55)}
.locale-cell.is-missing{border-color:rgba(245,158,11,.55);background:rgba(180,83,9,.15)}
.locale-cell label{font-size:11px;color:#94a3b8;text-transform:uppercase;letter-spacing:.05em;font-weight:700}
.locale-cell textarea{border-radius:8px;border:1px solid rgba(71,85,105,.55);background:rgba(15,23,42,.8);color:#e2e8f0;padding:8px;font-size:12px}
@media (max-width:980px){.locale-grid{grid-template-columns:1fr}}
</style>

