export interface TranslationLocaleCell {
  id: number;
  locale: string;
  value: string;
  is_translated: boolean;
  is_auto_generated: boolean;
  is_active: boolean;
  description?: string | null;
  updated_at: string | null;
}

export interface TranslationRow {
  id: number;
  group: string;
  key: string;
  source: string;
  is_translated: boolean;
  is_auto_generated: boolean;
  is_active: boolean;
  updated_at: string | null;
  locales: Record<string, TranslationLocaleCell>;
}

export interface TranslationsQuery {
  search: string;
  locale: string;
  group: string;
  source: string;
  translatedOnly: boolean;
  autogeneratedOnly: boolean;
  active: 'all' | 'active' | 'inactive';
  page: number;
  perPage: number;
}

export interface TranslationsMeta {
  current_page: number;
  last_page: number;
  per_page: number;
  total: number;
  groups: string[];
  sources: string[];
  locales: string[];
}

export interface TranslationUpsertPayload {
  group: string;
  key: string;
  source: string;
  description?: string | null;
  is_active: boolean;
  is_auto_generated: boolean;
  values: Record<string, string>;
}

