import { api } from '../../../services/api/client';
import type { ApiResponse } from '../../../types/response.types';
import type {
  TranslationRow,
  TranslationsMeta,
  TranslationUpsertPayload,
} from '../types/translations.types';

interface ListParams {
  search?: string;
  locale?: string;
  group?: string;
  source?: string;
  translated_only?: boolean;
  autogenerated_only?: boolean;
  active?: string;
  page?: number;
  per_page?: number;
}

export const translationsService = {
  async fetchTranslations(params: ListParams): Promise<{ items: TranslationRow[]; meta: TranslationsMeta }> {
    const response = await api.get<TranslationRow[]>('/v1/translations/manage', { params });
    const payload = response as ApiResponse<TranslationRow[]>;

    return {
      items: payload.data ?? [],
      meta: {
        current_page: Number((payload.meta as Record<string, unknown> | undefined)?.current_page ?? 1),
        last_page: Number((payload.meta as Record<string, unknown> | undefined)?.last_page ?? 1),
        per_page: Number((payload.meta as Record<string, unknown> | undefined)?.per_page ?? 10),
        total: Number((payload.meta as Record<string, unknown> | undefined)?.total ?? 0),
        groups: ((payload.meta as Record<string, unknown> | undefined)?.groups as string[] | undefined) ?? [],
        sources: ((payload.meta as Record<string, unknown> | undefined)?.sources as string[] | undefined) ?? [],
        locales: ((payload.meta as Record<string, unknown> | undefined)?.locales as string[] | undefined) ?? [],
      },
    };
  },

  async createTranslation(payload: TranslationUpsertPayload): Promise<void> {
    await api.post('/v1/translations/manage', payload);
  },

  async updateTranslation(id: number, payload: Omit<TranslationUpsertPayload, 'group' | 'key'> & { values: Record<string, string> }): Promise<void> {
    await api.put(`/v1/translations/manage/${id}`, payload);
  },

  async deleteTranslation(id: number): Promise<void> {
    await api.delete(`/v1/translations/manage/${id}`);
  },
};

