<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Create chat user devices table.
     *
     * WHY:
     * This table stores known user devices used for chat.
     * It allows the system to track read state per device:
     * browser, mobile, desktop app, tablet, etc.
     */
    public function up(): void
    {
        Schema::create('chat_user_devices', function (Blueprint $table) {
            $table->id()
                ->comment('Primary chat user device ID.');

            $table->uuid('uuid')
                ->unique()
                ->comment('Public unique device identifier.');

            $table->foreignId('user_id')
                ->constrained('users')
                ->cascadeOnDelete()
                ->comment('User who owns this device.');

            /**
             * Device identity.
             *
             * device_key should be generated on frontend and stored locally.
             * Example: localStorage chat_device_key.
             */
            $table->string('device_key', 128)
                ->comment('Stable per-browser/per-device key generated by the client.');

            $table->string('device_name')
                ->nullable()
                ->comment('Human-readable device name, for example Chrome on Windows.');

            $table->string('device_type', 32)
                ->default('browser')
                ->index()
                ->comment('Device type: browser, mobile, desktop, tablet, api, unknown.');

            /**
             * Optional client metadata.
             */
            $table->string('platform', 64)
                ->nullable()
                ->comment('Client platform, for example Windows, macOS, iOS, Android, Linux.');

            $table->string('browser', 64)
                ->nullable()
                ->comment('Browser name, for example Chrome, Firefox, Safari, Edge.');

            $table->string('app_version', 64)
                ->nullable()
                ->comment('Application/frontend version used by this device.');

            $table->string('ip_address', 45)
                ->nullable()
                ->comment('Last known IP address. Supports IPv4 and IPv6.');

            $table->text('user_agent')
                ->nullable()
                ->comment('Last known user agent string.');

            /**
             * Device state.
             */
            $table->boolean('is_active')
                ->default(true)
                ->index()
                ->comment('Whether this device is currently allowed to sync chat state.');

            $table->timestamp('last_seen_at')
                ->nullable()
                ->index()
                ->comment('Timestamp when this device was last seen.');

            $table->json('metadata')
                ->nullable()
                ->comment('Optional safe device metadata.');

            $table->timestamps();

            /**
             * One stable device key per user.
             */
            $table->unique(['user_id', 'device_key'], 'chat_user_devices_user_device_unique');

            /**
             * Common lookup indexes.
             */
            $table->index(['user_id', 'is_active'], 'chat_user_devices_user_active_idx');
            $table->index(['user_id', 'last_seen_at'], 'chat_user_devices_user_last_seen_idx');
            $table->index(['device_type', 'is_active'], 'chat_user_devices_type_active_idx');
        });

        DB::statement("ALTER TABLE chat_user_devices COMMENT = 'Stores user devices used for chat read state, sync and presence tracking.'");
    }

    /**
     * Drop chat user devices table.
     */
    public function down(): void
    {
        Schema::dropIfExists('chat_user_devices');
    }
};