[supervisord]
nodaemon=true
user=root

[program:queue-worker]
command=php artisan queue:work redis --queue=webhooks,realtime,notifications,activity,emails,default,low --sleep=1 --tries=3 --timeout=90 --backoff=10 --max-time=3600 --max-jobs=1000
directory=/var/www
autostart=true
autorestart=true
startretries=10
stopasgroup=true
killasgroup=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
